name: personal_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  hotkey_manager: ^0.2.3
  flutter_animate: ^4.5.2
  provider: ^6.1.5+1
  flutter_acrylic: ^1.1.4
  drift: ^2.32.1
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.3
  sqlite3: ^3.3.1
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  flutter_chat_core: ^2.9.0
  llm_json_stream: ^0.4.7
  flutter_bloc: ^9.1.1
  flyer_chat_text_stream_message: ^2.3.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  openai_dart: ^4.1.0
  equatable: ^2.0.8
  font_awesome_flutter: ^11.0.0
  google_fonts: ^8.0.2
  flyer_chat_text_message: ^2.6.0
  supabase_flutter: ^2.12.2
  file_picker: ^11.0.2
  crypto: ^3.0.7
  http: ^1.6.0
  syncable: ^1.0.3
  json_annotation: ^4.11.0
  connectivity_plus: ^7.1.1
  pasteboard: ^0.5.0

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.13.1
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true
