name: personal_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  hotkey_manager: ^0.2.3
  flutter_animate: ^4.5.2
  provider: ^6.1.5+1
  flutter_acrylic: ^1.1.4
  drift: ^2.32.1
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.3
  sqlite3: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
