import 'dart:math';

// For when AI is doing work anywhere else
const List<String> generatingTextNeutral = [
  "Thinking...",
  "Processing...",
  "Analyzing...",
  "Synthesizing...",
  "Considering...",
  "Gathering context...",
  "Optimizing...",
  "Evaluating...",
  "Reviewing data...",
  "Sorting thoughts...",
  "Refining...",
  "Calculating...",
  "Interpreting...",
  "Formulating...",
  "Structuring...",
  "Connecting dots...",
  "Deliberating...",
  "Pondering...",
  "Meditating...",
  "Examining...",
  "Scanning...",
  "Querying...",
  "Reasoning...",
  "Logic-ing...",
  "Verifying...",
  "Decoding...",
  "Encapsulating...",
  "Validating...",
  "Parsing...",
  "Drafting...",
  "Reflecting...",
  "Organizing...",
  "Structuring context...",
  "Finalizing...",
];

// For when AI is doing work in somewhere unserious
const List<String> generatingTextPlayful = [
  "Reticulating splines...",
  "Consulting the elder gods...",
  "Asking the magic 8-ball...",
  "Charging flux capacitors...",
  "Herding digital cats...",
  "Feeding the hamsters...",
  "Brewing a fresh pot of neural coffee...",
  "Counting to infinity (twice)...",
  "Teaching a cloud to sit...",
  "Spinning the hamster wheel...",
  "Negotiating with gravity...",
  "Convincing the bits to behave...",
  "Translating from binary to barks...",
  "Polishing the internet...",
  "De-fragmenting the universe...",
  "Inflating the ego...",
  "Deflating the hype...",
  "Adjusting the vibe...",
  "Sprinkling some magic...",
  "Waking up the sub-kernels...",
  "Reciting poetry to the CPU...",
  "Chasing laser pointers...",
  "Manifesting snacks...",
  "Searching for the Answer...",
  "Questioning everything...",
  "Checking for ghosts in the machine...",
  "Updating the simulation...",
  "Recalibrating the fun-o-meter...",
  "Tickling the transistors...",
  "Making a sandwich...",
  "Doing the digital tango...",
  "Polishing the crystal ball...",
  "Untangling the rainbow...",
  "Bouncing ideas off the moon...",
];

// For when AI is fixing or organizing
const List<String> generatingTextFixing = [
  "Untangling the spaghetti...",
  "Polishing the chrome...",
  "Tidying the workspace...",
  "Smoothing out the bumps...",
  "Realigning the chakras...",
  "Ironing out the creases...",
  "Washing the windows...",
  "Patching the holes...",
  "Cleaning the pipes...",
  "Tightening the screws...",
  "Mending the fences...",
  "Restoring order...",
  "Defusing the tension...",
  "Balancing the scales...",
  "Clearing the air...",
  "Dusting the shelves...",
  "Optimizing the flow...",
  "Refactoring reality...",
  "Debugging the void...",
  "Healing the data...",
  "Mending the broken bits...",
  "Straightening the horizons...",
  "Leveling the playing field...",
  "Sharpening the focus...",
  "Filtering the noise...",
  "Steadying the ship...",
  "Grounding the signals...",
  "Tuning the instruments...",
  "Stitching the seams...",
  "Knitting the data back together...",
  "Sweeping the floor...",
  "Oiling the gears...",
  "Tightening the knots...",
  "Calibrating the lens...",
  "Clearing the fog...",
];

// For when the AI is creating or generating some content or object
const List<String> generatingTextCreating = [
  "Forging new paths...",
  "Weaving the tapestry...",
  "Sculpting something beautiful...",
  "Painting with logic...",
  "Drafting the blueprints...",
  "Laying the bricks...",
  "Planting the seeds...",
  "Brewing the secret sauce...",
  "Sparking an idea...",
  "Igniting the creative engine...",
  "Carving the details...",
  "Baking the bread...",
  "Staging the scene...",
  "Composing the melody...",
  "Drafting the future...",
  "Assembling the pieces...",
  "Knitting the story...",
  "Fashioning the form...",
  "Molding the clay...",
  "Casting the spell...",
  "Spinning the web...",
  "Building the dream...",
  "Writing the script...",
  "Choreographing the dance...",
  "Mixing the ingredients...",
  "Developing the vision...",
  "Etching the memories...",
  "Generating the vibe...",
  "Constructing the narrative...",
  "Evolving the concept...",
  "Architecting the solution...",
  "Fostering growth...",
  "Cultivating ideas...",
  "Synthesizing brilliance...",
  "Crafting a masterpiece...",
];

String getRandomGeneratingText(List<String> texts) {
  if (texts.isEmpty) return "Loading...";
  return texts[Random().nextInt(texts.length)];
}
